name: Print

on:
    push:
        branches: [master]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: git checkout repo
              uses: actions/checkout@v6

            - name: Compile file
              run: gcc first.cpp -o a.out

            - name: Print Output
              run: ./a.out
