name: Print
run-name: This commit is push by ${{github.actor}}
on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout repo
        uses: actions/checkout@v4

      - name: Print all files
        run: ls -la

      - name: compile file
        run: g++ first.cpp -o a.out

      - name: Give Input
        run: echo "5" | ./first

      - name: Print Output
        run: ./a.out
