name: Run cpp file
run-name: Build trigger by ${{ github.actor }}

on:
    schedule:
        - cron: "0 0 * * *"

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Compile C++ file
              run: g++ first.cpp -o a.out

            - name: Running Cpp file
              run: ./a.out
